### ISSUE TITLE
Variable can be declared in for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-preety-1997#1]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-preety-1997/blob/6f08c722a1952ca70b12574a7e5c82bb655a7f29/reverse-using-iterators.js#L4

**Comment by kumaripreety** [comment]
This i is used outside the scope of for loop as well , so can't declare it in the for loop.
